const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const root = path.resolve(__dirname, '..')
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8')

test('C1 owns one persistent main-process path with every external audio source frozen', () => {
  const main = read('electron/main.js')
  const start = main.indexOf("persistentTaskRuntime.register('media.edit-audio-mix'")
  const end = main.indexOf("persistentTaskRuntime.register('media.edit-concat'", start)
  const executor = main.slice(start, end)
  assert.ok(start > 0)
  assert.match(executor, /decision\.kind !== 'media\.mix-audio'/)
  assert.match(executor, /assertEditDecisionList\(decision\)/)
  assert.match(executor, /validateMediaSources\(task\.spec\.sources\)/)
  assert.match(executor, /decision\.audioMix\?\.tracks/)
  assert.match(executor, /mediaEditService\.mixAudio/)
  assert.match(executor, /mediaEditService\.verify/)
  assert.match(executor, /mediaEditProjects\.recordEdit/)
  assert.match(main, /decision\.kind === 'media\.mix-audio'[\s\S]{0,100}'media\.edit-audio-mix'/)
  assert.match(main, /decision\.kind === 'media\.mix-audio'[\s\S]{0,180}\[sourcePath, \.\.\.decision\.audioMix\.tracks\.map/)
  assert.match(main, /type === 'media\.edit-audio-mix'/)
})

test('C1 renderer presents one natural-language task with track timeline, recovery and undo', () => {
  const panel = read('src/components/agent-panel/useMediaCreativeTasks.ts')
  const runtime = read('src/components/agent-panel/usePersistentTaskRuntime.ts')
  const types = read('src/types/global.d.ts')
  const projects = read('electron/media-edit-project-store.js')
  const router = read('src/components/agent-panel/intentRouter.ts')
  assert.match(panel, /decision\.kind === 'media\.mix-audio' \? 'audio-mix'/)
  assert.match(panel, /'media\.add-music', 'media\.mix-audio', 'media\.repair-audio', 'media\.rhythm-edit', 'media\.visual-effects'/)
  assert.match(panel, /专业多轨混音/)
  assert.match(panel, /对齐对白、音乐、环境声与音效/)
  assert.match(panel, /operation === 'audio-mix' \|\| operation === 'audio-repair' \|\| operation === 'rhythm' \? '音频'/)
  assert.match(panel, /runAudioMixAttachmentTask/)
  assert.match(panel, /我不会根据文件名猜/)
  assert.match(panel, /多轨音频规划失败/)
  assert.match(runtime, /runtimeTask\.type === 'media\.edit-audio-mix'/)
  assert.match(types, /kind: 'media\.trim'[\s\S]{0,240}'media\.mix-audio'/)
  assert.match(types, /strategy: 'multitrack-audio-mix-v1'/)
  assert.match(projects, /decision\?\.kind === 'media\.mix-audio'\) return 'mix-audio'/)
  assert.match(router, /多轨混音\|添加环境声\|添加音效\|对白闪避\|分段音量/)
  assert.match(router, /attachments\.length > 0 && await runAudioMixAttachmentTask\(text\)/)
})

test('C1 quality authority fails closed on missing PCM alignment, automation or ducking receipts', () => {
  const quality = read('electron/task-result-quality.js')
  for (const code of ['MULTITRACK_PROOF_MISSING', 'TRACK_ALIGNMENT_MISMATCH', 'TRACK_AUTOMATION_MISSING', 'DUCKING_RECEIPT_MISSING']) {
    assert.match(quality, new RegExp(code))
  }
  assert.match(quality, /taskType === 'media\.edit-audio-mix'/)
  assert.match(quality, /decoded-multitrack-pcm-v1/)
  assert.match(quality, /projectCapsule/)
})

test('C1 has an installed conversation acceptance that freezes three source hashes and requires quality 100', () => {
  const smokePath = path.join(root, 'scripts', 'smoke-packaged-audio-mix.mjs')
  assert.equal(fs.existsSync(smokePath), true)
  const smoke = read('scripts/smoke-packaged-audio-mix.mjs')
  assert.match(smoke, /media\.edit-audio-mix/)
  assert.match(smoke, /audioMixProof\?\.verdict !== 'matched'/)
  assert.match(smoke, /quality\?\.score !== 100/)
  assert.match(smoke, /projectCapsule\?\.canUndo !== true/)
  assert.match(smoke, /JSON\.stringify\(before\) !== JSON\.stringify\(after\)/)
})
