const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = path.join(__dirname, '..')
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8')

test('main process owns planning, frozen execution, recovery and cancellation for exact trim jobs', () => {
  const main = read('electron/main.js')
  assert.match(main, /compileEditDecisionList/)
  assert.match(main, /new MediaEditService\(\{ frames: videoFrames \}\)/)
  assert.match(main, /persistentTaskRuntime\.register\('media\.edit-trim'/)
  const executor = main.slice(main.indexOf("persistentTaskRuntime.register('media.edit-trim'"), main.indexOf("persistentTaskRuntime.register('media.edit-remove'"))
  assert.equal((executor.match(/validateMediaSources\(task\.spec\.sources\)/g) || []).length, 2, '剪辑前后都必须复核源文件指纹')
  assert.match(main, /mediaEditService\.trim\(\{[\s\S]{0,240}decision: task\.spec\.decision[\s\S]{0,240}signal/)
  assert.match(main, /checkpoint\(\{ stage: 'artifact-written', result/)
  assert.match(main, /ipcMain\.handle\('media:edit-plan'/)
  assert.match(main, /ipcMain\.handle\('media:trim'/)
  assert.match(main, /请明确说“保留第4秒到第20秒”或“删除第4秒到第8秒”/)
  assert.match(main, /type: decision\.kind === 'media\.remove-segment' \? 'media\.edit-remove' : 'media\.edit-trim'/)
  assert.match(main, /plannedMediaOutput\(sourcePath, decision\.output\.suffix, '\.mp4', requestId\)/)
})

test('main process persists an edit capsule before checkpointing and owns undo or redo navigation', () => {
  const main = read('electron/main.js')
  assert.match(main, /new MediaEditProjectStore\(\{ rootDir: path\.join\(app\.getPath\('userData'\), 'media-edit-projects'\) \}\)/)
  const executor = main.slice(main.indexOf("persistentTaskRuntime.register('media.edit-trim'"), main.indexOf("persistentTaskRuntime.register('media.edit-remove'"))
  assert.match(executor, /mediaEditProjects\.recordEdit\(\{[\s\S]{0,260}taskId: task\.id[\s\S]{0,260}sourcePath[\s\S]{0,260}outputPath/)
  assert.ok(executor.indexOf('mediaEditProjects.recordEdit') < executor.indexOf("checkpoint({ stage: 'artifact-written'"), '项目版本必须先持久化再收口任务检查点')
  assert.match(main, /ipcMain\.handle\('media:edit-history-plan'/)
  assert.match(main, /ipcMain\.handle\('media:edit-history'/)
  assert.match(main, /mediaEditProjects\.navigate\(\{ currentPath, direction: action\.action \}\)/)
})

test('preload exposes planning, trim execution, project navigation and the shared persistent cancel route', () => {
  const preload = read('electron/preload.js')
  const types = read('src/types/global.d.ts')
  assert.match(preload, /planEdit: \(input\) => ipcRenderer\.invoke\('media:edit-plan', input\)/)
  assert.match(preload, /planHistory: \(input\) => ipcRenderer\.invoke\('media:edit-history-plan', input\)/)
  assert.match(preload, /navigateHistory: \(input\) => ipcRenderer\.invoke\('media:edit-history', input\)/)
  assert.match(preload, /trim: \(input\) => ipcRenderer\.invoke\('media:trim', input\)/)
  assert.match(preload, /mediaTools:[\s\S]{0,600}cancel: \(requestId\) => ipcRenderer\.invoke\('media:task-cancel', requestId\)/)
  assert.match(types, /planEdit: \(input: \{ instruction: string; sourcePath: string \}/)
  assert.match(types, /planHistory: \(input: \{ instruction: string; currentPath: string \}/)
  assert.match(types, /navigateHistory: \(input: \{ instruction: string; currentPath: string \}/)
  assert.match(types, /trim: \(input: \{ instruction: string; sourcePath: string; requestId: string;/)
})

test('renderer routes only a main-process-confirmed edit plan into a visible recoverable task', () => {
  const router = read('src/components/agent-panel/intentRouter.ts')
  const tasks = read('src/components/agent-panel/useMediaCreativeTasks.ts')
  const panel = read('src/components/AgentPanel.tsx')
  const recovery = read('src/components/agent-panel/usePersistentTaskRuntime.ts')
  const dispatcher = read('src/components/agent-panel/taskCommandDispatcher.ts')
  const lifecycle = read('src/taskLifecycle.ts')
  assert.match(router, /if \(videoSrc[\s\S]{0,220}await runTrimTask\(text\)[\s\S]{0,80}return/)
  assert.ok(router.indexOf('await runTrimTask(text)') < router.indexOf('await runCompressTask(text)'))
  assert.match(tasks, /mediaTools\.planEdit\(\{ instruction: text, sourcePath \}\)/)
  assert.match(tasks, /mediaTools\.trim\(\{ sourcePath, instruction: text, requestId, workspaceTaskId:/)
  assert.match(tasks, /timelineReceipt/)
  assert.match(tasks, /result\.projectCapsule/)
  assert.match(tasks, /可直接说“撤销刚才的剪辑”/)
  assert.match(tasks, /ai-player-play-file/)
  assert.match(tasks, /case 'trim':/)
  assert.match(panel, /runTrimTask/)
  assert.match(recovery, /runtimeTask\.type === 'media\.edit-trim'/)
  assert.match(recovery, /isDownload \|\| isCreative \|\| isTimelineEdit/)
  assert.match(dispatcher, /case 'trim':[\s\S]{0,180}mediaTools\?\.cancel\(requestId\)/)
  assert.match(lifecycle, /'trim'/)
})

test('renderer routes a confirmed undo or redo action back to the project version and player', () => {
  const router = read('src/components/agent-panel/intentRouter.ts')
  const tasks = read('src/components/agent-panel/useMediaCreativeTasks.ts')
  const panel = read('src/components/AgentPanel.tsx')
  assert.match(router, /await runEditHistoryTask\(text\)/)
  assert.ok(router.indexOf('await runEditHistoryTask(text)') < router.indexOf('await runTrimTask(text)'))
  assert.match(tasks, /mediaTools\.planHistory\(\{ instruction: text, currentPath \}\)/)
  assert.match(tasks, /mediaTools\.navigateHistory\(\{ instruction: text, currentPath \}\)/)
  assert.match(tasks, /result\.versionCount/)
  assert.match(tasks, /ai-player-play-file/)
  assert.match(panel, /runEditHistoryTask/)
})

test('remove-segment decisions enter their own recoverable task and the shared edit project', () => {
  const main = read('electron/main.js')
  const executorStart = main.indexOf("persistentTaskRuntime.register('media.edit-remove'")
  const executorEnd = main.indexOf("persistentTaskRuntime.register('media.dedup'")
  const executors = main.slice(executorStart, executorEnd)
  assert.match(executors, /persistentTaskRuntime\.register\('media\.edit-remove'/)
  assert.match(executors, /decision\.kind !== 'media\.remove-segment'/)
  assert.match(executors, /mediaEditService\.removeSegment/)
  assert.match(executors, /mediaEditProjects\.recordEdit\(\{[\s\S]{0,260}taskId: task\.id/)
  assert.match(main, /type: decision\.kind === 'media\.remove-segment' \? 'media\.edit-remove' : 'media\.edit-trim'/)
  assert.match(main, /type === 'media\.edit-trim' \|\| type === 'media\.edit-remove'/)
})

test('renderer presents remove-segment as a recoverable edit with every timeline mapping', () => {
  const tasks = read('src/components/agent-panel/useMediaCreativeTasks.ts')
  const runtime = read('src/components/agent-panel/usePersistentTaskRuntime.ts')
  const types = read('src/types/global.d.ts')
  assert.match(tasks, /\['media\.trim', 'media\.remove-segment'\]\.includes\(decision\.kind\)/)
  assert.match(tasks, /removesSegment = decision\.kind === 'media\.remove-segment'/)
  assert.match(tasks, /timelineReceipt \|\| \[\]\)\.map/)
  assert.match(tasks, /start_remove_video_segment/)
  assert.match(runtime, /runtimeTask\.type === 'media\.edit-trim' \|\| runtimeTask\.type === 'media\.edit-remove'/)
  assert.match(types, /kind: 'media\.trim' \| 'media\.remove-segment'/)
})
