const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const read = (file) => fs.readFileSync(path.join(__dirname, '..', file), 'utf8')

test('main process owns persistent download scheduling and renderer can reconcile recovered jobs', () => {
  const main = read('electron/main.js')
  const preload = read('electron/preload.js')
  const types = read('src/types/global.d.ts')
  const panel = read('src/components/AgentPanel.tsx')
  const recoveryHook = read('src/components/agent-panel/usePersistentTaskRuntime.ts')
  const links = read('src/components/agent-panel/useLinkMediaTasks.ts')

  assert.match(main, /new PersistentTaskRuntime/)
  assert.match(main, /register\('download\.direct'/)
  assert.match(main, /register\('download\.site'/)
  assert.match(main, /startRecoverable\(\)/)
  assert.match(main, /ipcMain\.handle\('taskRuntime:list'/)
  assert.match(main, /ipcMain\.handle\('taskRuntime:approve'/)
  assert.match(main, /ipcMain\.handle\('taskRuntime:resume'/)
  assert.match(preload, /taskRuntime:\s*\{/)
  assert.match(types, /taskRuntime\?:\s*\{/)
  assert.match(panel, /usePersistentTaskRuntime\(docRequestIdRef\)/)
  assert.match(recoveryHook, /taskRuntime\?\.list\(\)/)
  assert.match(recoveryHook, /taskRuntime\?\.onEvent/)
  assert.match(recoveryHook, /persist\.hasHydrated\(\)/)
  assert.match(recoveryHook, /persist\.onFinishHydration/)
  assert.match(recoveryHook, /const stopHydration = useAgentStore\.persist\.onFinishHydration\(syncAll\)\s+if \(useAgentStore\.persist\.hasHydrated\(\)\) syncAll\(\)/)
  assert.match(recoveryHook, /agentplay-open-task-center/)
  assert.doesNotMatch(recoveryHook, /!existing && terminal && !fromEvent/)
  assert.doesNotMatch(recoveryHook, /if \(!useAgentStore\.persist\.hasHydrated\(\)\) return/)
  assert.match(recoveryHook, /if \(!existing\) store\.startTask/)
  assert.match(links, /workspaceTaskId:\s*executionTaskIdRef\.current/)
})
