const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const read = (file) => fs.readFileSync(path.join(__dirname, '..', file), 'utf8')

test('main, preload, UI and docs expose one declarative plugin and Skill manager', () => {
  const main = read('electron/main.js')
  const preload = read('electron/preload.js')
  const types = read('src/types/global.d.ts')
  const ui = read('src/components/MediaLibrary.tsx')
  const app = read('src/App.tsx')
  const docs = read('docs/PLUGINS_AND_SKILLS.md')
  const example = JSON.parse(read('examples/agentplay-plugin-video-notes/agentplay-plugin.json'))
  assert.match(main, /new PluginSkillService/)
  assert.match(main, /replacePluginContributions/)
  for (const channel of ['plugin:install', 'plugin:setEnabled', 'plugin:remove', 'plugin:refresh']) assert.match(main, new RegExp(channel))
  for (const method of ['install:', 'setEnabled:', 'remove:', 'refresh:']) assert.match(preload, new RegExp(method))
  assert.match(types, /PluginSkillInfo/)
  assert.match(ui, /安装插件包/)
  assert.match(ui, /已隔离停用/)
  assert.match(app, /setLibraryActionRequest/)
  assert.match(app, /actionRequest=\{libraryActionRequest\}/)
  assert.match(ui, /actionRequest\?\.action/)
  assert.match(docs, /声明式/)
  assert.match(docs, /不执行第三方/)
  assert.equal(example.schemaVersion, 1)
})
