const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { ProjectCapsuleStore } = require('../electron/project-capsule-store')

test('mixed materials, instructions and derived artifacts survive restart without duplicate content', (t) => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'agentplay-project-capsule-'))
  t.after(() => fs.rmSync(root, { recursive: true, force: true }))
  const video = path.join(root, 'video.mp4'); const subtitle = path.join(root, 'video.srt'); const report = path.join(root, 'report.docx')
  fs.writeFileSync(video, Buffer.alloc(2048, 1)); fs.writeFileSync(subtitle, '字幕'); fs.writeFileSync(report, Buffer.concat([Buffer.from('PK'), Buffer.alloc(2048)]))
  let ids = 0
  const store = new ProjectCapsuleStore({ rootDir: path.join(root, 'state'), idFactory: () => String(++ids), now: () => 1000 + ids })
  const capsule = store.recordTask({ projectId: 'project-1', taskId: 'task-1', type: 'outcome.workflow', instruction: '做成报告', sources: [video, subtitle, video], references: [{ kind: 'web', uri: 'https://example.com/source' }, { kind: 'web', uri: 'https://example.com/source' }], outputs: [report], operationKey: 'op-1' })
  assert.equal(capsule.materialCount, 2, '相同视频内容不得重复登记')
  assert.equal(capsule.artifactCount, 1)
  assert.equal(capsule.revision, 1)
  const restarted = new ProjectCapsuleStore({ rootDir: path.join(root, 'state') })
  assert.equal(restarted.get('project-1').instructions[0].text, '做成报告')
  assert.equal(restarted.get('project-1').references.length, 1, '相同网页来源不得重复登记')
  assert.deepEqual(restarted.get('project-1').artifacts[0].derivedFrom.length, 2)
  assert.equal(restarted.findReusable('project-1', 'op-1').outputs[0], report)
})

test('continuing from a prior artifact stays in the same project and advances the current revision', (t) => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'agentplay-project-continue-'))
  t.after(() => fs.rmSync(root, { recursive: true, force: true }))
  const source = path.join(root, 'source.txt'); const first = path.join(root, 'first.docx'); const second = path.join(root, 'second.pdf')
  fs.writeFileSync(source, 'source'); fs.writeFileSync(first, Buffer.concat([Buffer.from('PK'), Buffer.alloc(100)])); fs.writeFileSync(second, '%PDF-1.4\n%%EOF')
  const store = new ProjectCapsuleStore({ rootDir: path.join(root, 'state') })
  const one = store.recordTask({ projectId: 'project-x', taskId: 'one', instruction: '先做Word', sources: [source], outputs: [first] })
  assert.equal(store.resolveProjectId([first]), one.projectId)
  const two = store.recordTask({ projectId: store.resolveProjectId([first]), taskId: 'two', instruction: '继续改成PDF', sources: [first], outputs: [second] })
  assert.equal(two.projectId, one.projectId)
  assert.equal(two.revision, 2)
  assert.equal(two.currentPath, second)
  assert.equal(store.get(one.projectId).instructions.at(-1).text, '继续改成PDF')
  const project = store.get(one.projectId)
  assert.equal(project.materials.length, 1, '上一轮成果作为输入时不得重复登记成原始素材')
  assert.equal(project.artifacts[1].derivedFrom[0], project.artifacts[0].id, '第二版成果必须指向上一版成果')
})

test('changed derived files invalidate reuse and corrupt history fails closed', (t) => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'agentplay-project-invalid-'))
  t.after(() => fs.rmSync(root, { recursive: true, force: true }))
  const source = path.join(root, 'source.txt'); const output = path.join(root, 'output.txt')
  fs.writeFileSync(source, 'source'); fs.writeFileSync(output, 'result')
  const stateDir = path.join(root, 'state')
  const store = new ProjectCapsuleStore({ rootDir: stateDir })
  store.recordTask({ projectId: 'project-z', taskId: 'one', sources: [source], outputs: [output], operationKey: 'same' })
  fs.appendFileSync(output, 'changed')
  assert.throws(() => store.findReusable('project-z', 'same'), /项目文件已发生变化/)
  const corruptDir = path.join(root, 'corrupt'); fs.mkdirSync(corruptDir); fs.writeFileSync(path.join(corruptDir, 'project-capsules-v1.json'), '{broken')
  const corrupt = new ProjectCapsuleStore({ rootDir: corruptDir })
  assert.throws(() => corrupt.list(), /项目胶囊历史损坏/)
  assert.equal(fs.readFileSync(path.join(corruptDir, 'project-capsules-v1.json'), 'utf8'), '{broken')
})

test('main and preload expose read-only project capsule inspection', () => {
  const root = path.join(__dirname, '..')
  const main = fs.readFileSync(path.join(root, 'electron', 'main.js'), 'utf8')
  const preload = fs.readFileSync(path.join(root, 'electron', 'preload.js'), 'utf8')
  assert.match(main, /ipcMain\.handle\('projects:list'/)
  assert.match(main, /ipcMain\.handle\('projects:get'/)
  assert.match(preload, /projects: \{/)
  assert.match(preload, /ipcRenderer\.invoke\('projects:list'\)/)
})
