const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const root = path.resolve(__dirname, '..')
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8')

test('C3 planning and execution stay in the main process with frozen video and music snapshots', () => {
  const main = read('electron/main.js')
  const start = main.indexOf("registerGovernedMediaEdit('media.rhythm-edit'")
  const end = main.indexOf("registerGovernedMediaEdit('media.edit-concat'", start)
  const executor = main.slice(start, end)
  assert.ok(start > 0)
  assert.match(main, /matchesRhythmEditInstruction/)
  assert.match(main, /rhythmEditPlanner\.plan/)
  assert.match(executor, /assertEditDecisionList\(decision\)/)
  assert.match(executor, /validateMediaSources\(task\.spec\.sources\)/)
  assert.match(executor, /mediaEditService\.rhythmEdit/)
  assert.match(executor, /mediaEditService\.verifyRhythmEdit/)
  assert.match(main, /decision\.kind === 'media\.rhythm-edit'[\s\S]{0,100}'media\.rhythm-edit'/)
  assert.match(main, /decision\.kind === 'media\.rhythm-edit'[\s\S]{0,180}assertAllowedPath\(decision\.music/)
})

test('C3 renderer shows the frozen plan before execution and restores a named rhythm task', () => {
  const panel = read('src/components/agent-panel/useMediaCreativeTasks.ts')
  const runtime = read('src/components/agent-panel/usePersistentTaskRuntime.ts')
  const router = read('src/components/agent-panel/intentRouter.ts')
  const types = read('src/types/global.d.ts')
  const projects = read('electron/media-edit-project-store.js')
  assert.match(panel, /rhythmEdit\?\.confirmationRequired/)
  assert.match(panel, /plan\?\.review\?\.summary && !plan\?\.decision/)
  assert.match(panel, /真实节拍：/)
  assert.match(panel, /高潮区加密/)
  assert.match(panel, /operation === 'rhythm'/)
  assert.match(panel, /rhythmRequested/)
  assert.match(runtime, /isRhythmEdit = runtimeTask\.type === 'media\.rhythm-edit'/)
  assert.match(runtime, /节拍剪辑与高潮对齐/)
  assert.match(router, /按音乐节拍\|卡点剪辑\|高潮对齐\|片尾自然收束/)
  assert.match(types, /strategy: 'beat-synced-jump-cut-v1'/)
  assert.match(projects, /decision\?\.kind === 'media\.rhythm-edit'\) return 'rhythm-edit'/)
})

test('C3 quality gate requires decoded beats, visible cuts, denser highlight and two-sided tail fade', () => {
  const quality = read('electron/task-result-quality.js')
  for (const code of ['BEAT_EVIDENCE_MISSING', 'BEAT_CUT_NOT_VISIBLE', 'HIGHLIGHT_DENSITY_MISMATCH', 'MUSIC_ALIGNMENT_MISSING', 'TAIL_FADE_MISSING']) assert.match(quality, new RegExp(code))
  assert.match(quality, /taskType === 'media\.rhythm-edit'/)
  assert.match(quality, /decoded-beat-cut-proof-v1/)
})

test('C3 has an installed confirmation-first acceptance with quality 100 and source integrity', () => {
  const smokePath = path.join(root, 'scripts', 'smoke-packaged-rhythm-edit.mjs')
  assert.equal(fs.existsSync(smokePath), true)
  const smoke = read('scripts/smoke-packaged-rhythm-edit.mjs')
  assert.match(smoke, /media.rhythm-edit/)
  assert.match(smoke, /beforeTasks/)
  assert.match(smoke, /C3确认前不应创建持久任务/)
  assert.match(smoke, /quality\?\.score !== 100/)
  assert.match(smoke, /visibleCutRatio < 0.5/)
  assert.match(smoke, /musicCorrelation < 0.02/)
  assert.match(smoke, /安装态C3修改了源视频或音乐/)
})
