const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const roadmap = fs.readFileSync(path.join(__dirname, '..', 'ROADMAP.md'), 'utf8')

function section(start, end) {
  const startAt = roadmap.indexOf(start)
  assert.notEqual(startAt, -1, `missing roadmap section: ${start}`)
  const endAt = end ? roadmap.indexOf(end, startAt + start.length) : roadmap.length
  assert.notEqual(endAt, -1, `missing roadmap boundary: ${end}`)
  return roadmap.slice(startAt, endAt)
}

function checkboxCount(content, checked) {
  const marker = checked ? 'x' : ' '
  return (content.match(new RegExp(`^- \\[${marker}\\] `, 'gm')) || []).length
}

test('0.8.0 is feature-frozen while signed public release remains incomplete', () => {
  const content = section('### 0.8.0 冻结与发布收尾', '### 0.9.0：')
  assert.match(content, /功能开发完成率：\*\*100%（已冻结）\*\*/)
  assert.match(content, /稳定公开发布闭环：\*\*50%（3\/6）\*\*/)
  assert.equal(checkboxCount(content, true), 3)
  assert.equal(checkboxCount(content, false), 3)
  assert.match(content, /SignPath/)
  assert.match(content, /不得把未签名候选写成稳定公开版/)
  assert.match(content, /本机稳定安装程序版本为 0\.8\.0/)
  assert.match(content, /GitHub 最新公开产品 Release 仍是 `v0\.7\.6`/)
  assert.match(content, /“0\.8\.0 功能开发完成”与“0\.8\.0 签名公开发布完成”必须分开表述/)
})

test('0.9.0 reports strict closure separately from implementation coverage against the fixed denominator', () => {
  const content = section('### 0.9.0：', '### 0.9.1：')
  assert.match(content, /严格交付闭环：\*\*100%（25\/25）\*\*/)
  assert.match(content, /实质代码覆盖：\*\*100%（25\/25）\*\*/)
  assert.equal(checkboxCount(content, true), 30, 'five reusable foundations plus twenty-five completed features')
  assert.equal(checkboxCount(content, false), 0)
  assert.equal((content.match(/（已实现待收口）/g) || []).length, 0)
  assert.equal((content.match(/（未实现）/g) || []).length, 0)
  assert.match(content, /#### C\. 按成果自动编排工作流（5\/5 闭环，5\/5 有代码）/)
  assert.match(content, /#### D\. 自然语言影音编辑 Agent v1（5\/5 闭环，5\/5 有代码）/)
  assert.match(content, /#### E\. 后台完成与主动交付（5\/5 闭环，5\/5 有代码）/)
  assert.match(content, /#### A\. 项目胶囊与持续记忆（5\/5 闭环，5\/5 有代码）/)
  assert.match(content, /#### B\. 任意文件与链接的统一理解（5\/5 闭环，5\/5 有代码）/)
  assert.match(content, /审计基线：`3fa4b5b`/)
  assert.match(content, /相对 `master` 有 49 个提交、115 个文件发生变化、14843 行新增/)
  assert.match(content, /135 个自动测试文件、43 个安装态 smoke 脚本/)
  assert.match(content, /784 tests、784 pass、0 fail、0 skip/)
  assert.match(content, /25 项已形成统一协议/)
  assert.match(content, /不代表未签名安装包已经成为稳定公开版/)
  assert.match(content, /EditDecisionList v1/)
  assert.match(content, /第 4 秒到第 20 秒/)
  assert.match(content, /合法公版\/授权录音/)
  assert.match(content, /不得擅自下载商业录音/)
  assert.match(content, /轻量时间线回执、预览、撤销/)
})

test('0.9.1 records completed semantic and professional visual groups without overstating later work', () => {
  const content = section('### 0.9.1：', '### 0.9.2 ')
  assert.match(content, /功能交付完成率：\*\*92%（23\/25）\*\*/)
  assert.equal(checkboxCount(content, true), 23)
  assert.equal(checkboxCount(content, false), 2)
  assert.match(content, /#### A\. 语义剪辑（5\/5）/)
  assert.match(content, /删掉废话、停顿、重复和跑题段落/)
  assert.match(content, /多轨对白、音乐、环境声和音效/)
  assert.match(content, /个人编辑 Skill/)
  assert.match(content, /不以复刻剪映全部界面为目标/)
  assert.match(content, /audio-silencedetect-v1/)
  assert.match(content, /质量95通过/)
  assert.match(content, /废话、重复、跑题的语义证据.*尚未完成/)
  assert.match(content, /This operation was aborted/)
  assert.match(content, /模型响应超时/)
  assert.match(content, /subtitle-cue-cleanup-v1/)
  assert.match(content, /8\.222秒成片/)
  assert.match(content, /嵌在有效语句中的词、非紧邻重复和语义近似句均不自动删除/)
  assert.match(content, /句中口头禅、非紧邻或语义重复、跑题识别和五类素材人工标定尚未完成/)
  assert.match(content, /第三个纵向切片/)
  assert.match(content, /确认前不创建持久任务/)
  assert.match(content, /7\.222秒成片/)
  assert.match(content, /801 tests、801 pass、0 fail、0 skip/)
  assert.match(content, /逐词时间戳生成、语义近似重复、跑题证据与五类素材人工标定仍未完成/)
  assert.match(content, /第四个纵向切片/)
  assert.match(content, /DTW tiny/)
  assert.match(content, /11\.74–12\.58秒边界/)
  assert.match(content, /2\.62–3\.48秒/)
  assert.match(content, /805 tests、805 pass、0 fail、0 skip/)
  assert.match(content, /语义近似重复、跑题证据与五类素材人工标定尚未完成/)
  assert.match(content, /第五个纵向切片/)
  assert.match(content, /model-semantic-review-v1/)
  assert.match(content, /内置0\.5B轻量模型明确禁止作为删片依据/)
  assert.match(content, /不得超过字幕条数35%/)
  assert.match(content, /模型调用次数严格为1/)
  assert.match(content, /810 tests、809 pass、0 fail、1项外部网络条件跳过/)
  assert.match(content, /镜头证据交叉验证与访谈、课程、剧情、产品介绍、竖屏口播五类人工标定尚未完成/)
  assert.match(content, /第六个纵向切片/)
  assert.match(content, /before\/middle\/after三帧/)
  assert.match(content, /safe\/unsafe\/uncertain/)
  assert.match(content, /1次字幕请求和1次六帧视觉请求/)
  assert.match(content, /814 tests、814 pass、0 fail、0 skip/)
  assert.match(content, /访谈、课程、剧情、产品介绍、竖屏口播五类真实素材人工标定尚未完成/)
  assert.match(content, /第七个纵向切片（A1闭环并正式勾选）/)
  assert.match(content, /TP5、FP0、FN0、unsafe0、processingFailure0/)
  assert.match(content, /precision=1、recall=1/)
  assert.match(content, /真实`agnes-2\.5-flash`/)
  assert.match(content, /824 tests、824 pass、0 fail、0 skip/)
  assert.match(content, /A5的全组五类标定仍需等A2–A4完成后再勾选/)
  assert.match(content, /第八个纵向切片（A2首段/)
  assert.match(content, /subtitle-exact-quote-v1/)
  assert.match(content, /第九个纵向切片（A2第二段/)
  assert.match(content, /model-topic-selection-v1/)
  assert.match(content, /831 tests、831 pass、0 fail、0 skip/)
  assert.match(content, /第十个纵向切片（A2闭环并正式勾选）/)
  assert.match(content, /whisper-dtw-phrase-start-v1/)
  assert.match(content, /独立DTW证据得到目标短语3\.50–6\.32秒/)
  assert.match(content, /837 tests、836 pass、0 fail、1项外部网络条件skip/)
  assert.match(content, /默认文件并发固定为2/)
  assert.match(content, /A组更新为2\/5，0\.9\.1更新为2\/25=8%/)
  assert.match(content, /第十一个纵向切片（A3闭环并正式勾选）/)
  assert.match(content, /media-auto-inspection-v1/)
  assert.match(content, /843 tests、843 pass、0 fail、0 skip/)
  assert.match(content, /A组更新为3\/5，0\.9\.1更新为3\/25=12%/)
  assert.match(content, /第十二个纵向切片（A4闭环并正式勾选）/)
  assert.match(content, /shared-evidence-long-video-versions-v1/)
  assert.match(content, /模型严格只调用1次/)
  assert.match(content, /850 tests、850 pass、0 fail、0 skip/)
  assert.match(content, /A组更新为4\/5，0\.9\.1更新为4\/25=16%/)
  assert.match(content, /第十三个纵向切片（A5闭环并正式勾选）/)
  assert.match(content, /precision=1、recall=0\.9545/)
  assert.match(content, /minimumExportQuality100/)
  assert.match(content, /855 tests、854 pass、0 fail、1项外部Archive网络条件skip/)
  assert.match(content, /A组5\/5闭环，0\.9\.1更新为5\/25=20%/)
  assert.match(content, /#### B\. 专业画面编辑（5\/5）/)
  assert.match(content, /第十四个纵向切片（B1闭环并正式勾选）/)
  assert.match(content, /安装态一句话同时执行8类效果/)
  assert.match(content, /865 tests、865 pass、0 fail、0 skip/)
  assert.match(content, /B组更新为1\/5，0\.9\.1更新为6\/25=24%/)
  assert.match(content, /第十五个纵向切片（B2闭环并正式勾选）/)
  assert.match(content, /media\.smart-reframe/)
  assert.match(content, /红\/蓝目标像素质心分别为x=50\/101与x=50\/101/)
  assert.match(content, /873 tests、871 pass、0 fail、2项Archive外部网络条件skip/)
  assert.match(content, /B组更新为2\/5，0\.9\.1更新为7\/25=28%/)
  assert.match(content, /第十六个纵向切片（B3闭环并正式勾选）/)
  assert.match(content, /media\.visual-repair/)
  assert.match(content, /运动幅度11\.561→6\.466/)
  assert.match(content, /881 tests、878 pass、0 fail、3项外部网络条件skip/)
  assert.match(content, /B组更新为3\/5，0\.9\.1更新为8\/25=32%/)
  assert.match(content, /第十七个纵向切片（B4闭环并正式勾选）/)
  assert.match(content, /abstract-style-blueprint-v1/)
  assert.match(content, /rawReportSentToShotModel=false/)
  assert.match(content, /887 tests、886 pass、0 fail、1项外部网络条件skip/)
  assert.match(content, /B组更新为4\/5，0\.9\.1更新为9\/25=36%/)
  assert.match(content, /第十八个纵向切片（B5闭环并正式勾选）/)
  assert.match(content, /unified-visual-export-qc-v1/)
  assert.match(content, /UNEXPECTED_BLACK_BARS/)
  assert.match(content, /890 tests、888 pass、0 fail、2项Archive外部网络条件skip/)
  assert.match(content, /B组5\/5闭环，0\.9\.1更新为10\/25=40%/)
  assert.match(content, /#### C\. 专业音频与音乐（5\/5）/)
  assert.match(content, /第十九个纵向切片（C1闭环并正式勾选）/)
  assert.match(content, /multitrack-audio-mix-v1/)
  assert.match(content, /3\/3外部轨对齐、2段音量自动化、2轨对白闪避/)
  assert.match(content, /911 tests、910 pass、0 fail、1项Archive\.org外部网络条件skip/)
  assert.match(content, /C组更新为1\/5，0\.9\.1更新为11\/25=44%/)
  assert.match(content, /第二十个纵向切片（C2闭环并正式勾选）/)
  assert.match(content, /ffmpeg-audio-repair-v1/)
  assert.match(content, /restoresSpeech=false/)
  assert.match(content, /不是AI专业分轨/)
  assert.match(content, /925 tests、924 pass、0 fail、1项Archive\.org外网条件skip/)
  assert.match(content, /C组更新为2\/5，0\.9\.1更新为12\/25=48%/)
  assert.match(content, /第二十一个纵向切片（C3闭环并正式勾选）/)
  assert.match(content, /decoded-pcm-onset-grid-v1/)
  assert.match(content, /beat-synced-jump-cut-v1/)
  assert.match(content, /高潮平均切镜0\.500秒、普通段0\.907秒/)
  assert.match(content, /940 tests、940 pass、0 fail、0 skip/)
  assert.match(content, /C组更新为3\/5，0\.9\.1更新为13\/25=52%/)
  assert.match(content, /第二十二个纵向切片（C4闭环并正式勾选）/)
  assert.match(content, /internet-archive-license-filter-v1/)
  assert.match(content, /Public Domain Mark 1\.0、CC0 1\.0、CC BY 3\.0\/4\.0/)
  assert.match(content, /agentplay\.licensed-music-receipt/)
  assert.match(content, /3,782,661字节/)
  assert.match(content, /948 tests、948 pass、0 fail、0 skip/)
  assert.match(content, /C组更新为4\/5，0\.9\.1更新为14\/25=56%/)
  assert.match(content, /第二十三个纵向切片（C5闭环并正式勾选）/)
  assert.match(content, /unified-audio-export-qc-v1/)
  assert.match(content, /matched-user-policy/)
  assert.match(content, /UNIFIED_AUDIO_QC_FAILED/)
  assert.match(content, /-16\.0 LUFS、-11\.6 dBTP/)
  assert.match(content, /声画起点差0\.023秒\/终点差0秒/)
  assert.match(content, /959 tests、959 pass、0 fail、0 skip/)
  assert.match(content, /C组5\/5闭环，0\.9\.1更新为15\/25=60%/)
  assert.match(content, /#### D\. 专业字幕与包装（5\/5）/)
  assert.match(content, /第二十四个纵向切片（D1闭环并正式勾选）/)
  assert.match(content, /acoustic-speaker-karaoke-v1/)
  assert.match(content, /说话人序列`0,1,0,1`/)
  assert.match(content, /29个DTW词对应29个卡拉OK标签/)
  assert.match(content, /D组更新为1\/5，0\.9\.1更新为16\/25=64%/)
  assert.match(content, /第二十五个纵向切片（D2闭环并正式勾选）/)
  assert.match(content, /ass-brand-package-v1/)
  assert.match(content, /标题差0\.0673、两章0\.0087\/0\.0094、人物0\.0051、角标0\.0537、片尾0\.026/)
  assert.match(content, /975 tests、975 pass、0 fail、0 skip/)
  assert.match(content, /D组更新为2\/5，0\.9\.1更新为17\/25=68%/)
  assert.match(content, /第二十六个纵向切片（D3闭环并正式勾选）/)
  assert.match(content, /ordered-subtitle-transform-v1/)
  assert.match(content, /改字1、合并1、拆分1、整体提前0\.5秒、本机英译中和强调风格/)
  assert.match(content, /981 tests、981 pass、0 fail、0 skip/)
  assert.match(content, /D组更新为3\/5，0\.9\.1更新为18\/25=72%/)
  assert.match(content, /第二十七个纵向切片（D4闭环并正式勾选）/)
  assert.match(content, /responsive-ass-layout-v1/)
  assert.match(content, /像素差依次0\.0369\/0\.0313\/0\.0497\/0\.0448\/0\.0791\/0\.0665/)
  assert.match(content, /986 tests、986 pass、0 fail、0 skip/)
  assert.match(content, /D组更新为4\/5，0\.9\.1更新为19\/25=76%/)
  assert.match(content, /第二十八个纵向切片（D5闭环并正式勾选）/)
  assert.match(content, /single-render-subtitle-preview-burn-v1/)
  assert.match(content, /预览路径、交付路径与成果SHA-256必须完全相同/)
  assert.match(content, /三条活跃时刻相对源片像素差为1\.3008\/0\.8350\/1\.4209/)
  assert.match(content, /990 tests、990 pass、0 fail、0 skip/)
  assert.match(content, /D组5\/5闭环，0\.9\.1更新为20\/25=80%/)
  assert.match(content, /#### E\. AI 素材、个人风格与批处理（3\/5）/)
  assert.match(content, /第二十九个纵向切片（E1闭环并正式勾选）/)
  assert.match(content, /ai-generated-asset-bundle-v1/)
  assert.match(content, /审批对象消费前模型\/生图调用严格为0/)
  assert.match(content, /ai-text\+system-speech/)
  assert.match(content, /ai-designed\+deterministic-synthesis/)
  assert.match(content, /sourceMediaUploaded=false/)
  assert.match(content, /995 tests、995 pass、0 fail、0 skip/)
  assert.match(content, /E组更新为1\/5，0\.9\.1更新为21\/25=84%/)
  assert.match(content, /第三十个纵向切片（E2闭环并正式勾选）/)
  assert.match(content, /personal-edit-skills-v1/)
  assert.match(content, /revision4与digest跨重启一致/)
  assert.match(content, /当次明确说出的节奏、字幕样式或LUFS永远优先/)
  assert.match(content, /音乐文件全段/)
  assert.match(content, /1000 tests、1000 pass、0 fail、0 skip/)
  assert.match(content, /E组更新为2\/5，0\.9\.1更新为22\/25=88%/)
  assert.match(content, /第三十一个纵向切片（E3闭环并正式勾选）/)
  assert.match(content, /independent-media-edit-batch-v1/)
  assert.match(content, /MEDIA_RANGE_OUT_OF_BOUNDS/)
  assert.match(content, /repeatedCompletedItems=0/)
  assert.match(content, /1003 tests、1003 pass、0 fail、0 skip/)
  assert.match(content, /E组更新为3\/5，0\.9\.1更新为23\/25=92%/)
})

test('roadmap reflects the current public source and stable release boundary', () => {
  assert.doesNotMatch(roadmap, /本轮尚未推送或公开发布/)
  assert.doesNotMatch(roadmap, /0\.7\.6` 公开发布仍需完成/)
  assert.match(roadmap, /源码已通过 PR #16 合入公开 `master`/)
  assert.match(roadmap, /`0\.7\.6` 已完成公开 Release/)
})
