const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const read = (name) => fs.readFileSync(path.join(__dirname, '..', name), 'utf8')

test('main process plans, snapshots, persists and verifies visual effect decisions', () => {
  const main = read('electron/main.js')
  const registry = read('electron/media-edit-executor-registry.js')
  const service = read('electron/media-edit-service.js')
  const quality = read('electron/task-result-quality.js')
  assert.match(main, /matchesVisualEffectInstruction/)
  assert.match(main, /compileVisualEffectDecision/)
  assert.match(main, /registerGovernedMediaEdit\('media\.edit-visual-effects'/)
  assert.match(main, /mediaEditExecutors\.execute/)
  assert.match(registry, /this\.service\.visualEffects/)
  assert.match(main, /decision\.effectSources/)
  assert.match(service, /async visualEffects\(/)
  assert.match(service, /xfade=transition=fade/)
  assert.match(service, /acrossfade=d=/)
  assert.match(service, /effectReceipt/)
  assert.match(quality, /taskType === 'media\.edit-visual-effects'/)
  assert.match(quality, /EFFECT_CHANGE_MISSING/)
})

test('renderer, types and persistent recovery surface visual effects through the same conversation', () => {
  const hook = read('src/components/agent-panel/useMediaCreativeTasks.ts')
  const runtime = read('src/components/agent-panel/usePersistentTaskRuntime.ts')
  const types = read('src/types/global.d.ts')
  assert.match(hook, /media\.visual-effects/)
  assert.match(hook, /应用视觉效果/)
  assert.match(hook, /尺寸\/时长\/像素变化核验/)
  assert.match(runtime, /media\.edit-visual-effects/)
  assert.match(types, /'media\.visual-effects'/)
  assert.match(types, /effectReceipt\?:/)
})
